#!/usr/bin/env bun

import { $ } from "bun"
import { parseArgs } from "util"
import { clean } from "./clean"

const jb = "packages/kilo-jetbrains"
const props = `${jb}/gradle.properties`
const pkg = `${jb}/package.json`
const zip = `${jb}/backend/build/generated/kilo-cli-res/kilo-cli.zip`
const hint = `${jb}/.gradle/kilo-cli-pin.properties`

const arg = Bun.argv[2]
const cmd = arg && !arg.startsWith("-") ? arg : undefined
const { values } = parseArgs({
  args: cmd ? Bun.argv.slice(3) : Bun.argv.slice(2),
  options: {
    "no-verify": { type: "boolean", default: false },
    help: { type: "boolean", short: "h", default: false },
  },
})

if (values.help || !cmd) {
  console.log(`
Usage: bun .kilo/skills/jetbrains-cli-pin/script/cli-pin.ts <command> [--no-verify]

Commands:
  pin      Pin the JetBrains plugin to the latest released CLI. Cleans artifacts,
           sets kilo.cli.pinned=true, bumps package.json to the latest release,
           then verifies with a cold gradle build (needs network + Java 21).
  unpin    Use the local repo CLI. Cleans artifacts, sets kilo.cli.pinned=false,
           fresh-builds and stages the repo CLI, then verifies with typecheck.
  regen    Fast dev loop: rebuild + restage the local repo CLI (requires unpinned).
  clean    Remove all CLI/pin build artifacts and binaries in the current worktree.

Options:
  --no-verify   Skip the gradle verification build (rewrites + clean only).

Run from the repository root of the worktree you want to affect.
`)
  process.exit(values.help ? 0 : 1)
}

async function pinned() {
  const text = await Bun.file(props).text()
  const line = text.split(/\r?\n/).find((l) => l.startsWith("kilo.cli.pinned="))
  return (line?.split("=", 2)[1]?.trim().toLowerCase() ?? "true") === "true"
}

async function setPinned(value: boolean) {
  const text = await Bun.file(props).text()
  if (!/^kilo\.cli\.pinned=.*$/m.test(text)) throw new Error(`kilo.cli.pinned not found in ${props}`)
  await Bun.write(props, text.replace(/^kilo\.cli\.pinned=.*$/m, `kilo.cli.pinned=${value}`))
}

function bunPath() {
  return Bun.which("bun") ?? process.execPath
}

async function writeBunHint() {
  const path = bunPath()
  await $`mkdir -p ${jb}/.gradle`
  await Bun.write(hint, `# Generated by jetbrains-cli-pin so IDE-launched Gradle can find Bun in repo CLI mode.\nbun.path=${path}\n`)
  console.log(`Wrote Bun path hint for repo CLI mode: ${path}`)
}

async function removeBunHint() {
  await $`rm -f ${hint}`.nothrow()
}

async function report() {
  const version = (await Bun.file(pkg).json()).version
  console.log(`\nState: kilo.cli.pinned=${await pinned()}, package.json version=${version}`)
}

if (cmd === "pin") {
  await clean()
  await setPinned(true)
  await removeBunHint()
  // set-pin.ts bumps package.json to the latest release and refuses versions with
  // missing runtime assets, so we do not reimplement release/asset validation.
  await $`bun .kilo/skills/release-jetbrains/script/set-pin.ts --latest`
  if (!values["no-verify"]) {
    // Cold pinned build downloads the pinned CLI release via generateOpenApiSpec.
    await $`./gradlew clean typecheck --no-configuration-cache`.cwd(jb)
  }
  await report()
} else if (cmd === "unpin") {
  await clean()
  await setPinned(false)
  await writeBunHint()
  // build.ts does rm -rf dist internally, producing a fresh single-platform binary.
  await $`./gradlew :backend:buildRepoCli --no-configuration-cache`.cwd(jb)
  // stageRepoCli has upToDateWhen{false}; force it so the staged zip matches this build.
  await $`./gradlew :backend:stageRepoCli --no-configuration-cache`.cwd(jb)
  if (!(await Bun.file(zip).exists())) throw new Error(`Expected staged CLI at ${zip} after unpin`)
  if (!values["no-verify"]) {
    await $`./gradlew typecheck --no-configuration-cache`.cwd(jb)
  }
  await report()
} else if (cmd === "regen") {
  if (await pinned()) throw new Error("regen requires the unpinned state; run 'unpin' first")
  await writeBunHint()
  await $`rm -rf packages/opencode/dist`
  await $`./gradlew :backend:buildRepoCli --no-configuration-cache`.cwd(jb)
  await $`./gradlew :backend:stageRepoCli --no-configuration-cache`.cwd(jb)
  if (!(await Bun.file(zip).exists())) throw new Error(`Expected staged CLI at ${zip} after regen`)
  await report()
} else if (cmd === "clean") {
  await clean()
  await report()
} else {
  throw new Error(`Unknown command '${cmd}'. Run with --help for usage.`)
}
